export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_FINANCE_BEGIN = "CREATE_FINANCE_BEGIN";
export const CREATE_FINANCE_SUCCESS = "CREATE_FINANCE_SUCCESS";
export const CREATE_FINANCE_ERROR = "CREATE_FINANCE_ERROR";

export const GET_FINANCES_BEGIN = "GET_FINANCES_BEGIN";
export const GET_FINANCES_SUCCESS = "GET_FINANCES_SUCCESS";

export const SET_EDIT_FINANCE = "SET_EDIT_FINANCE";

export const DELETE_FINANCE_BEGIN = "DELETE_FINANCE_BEGIN";

export const EDIT_FINANCE_BEGIN = "EDIT_FINANCE_BEGIN";
export const EDIT_FINANCE_SUCCESS = "EDIT_FINANCE_SUCCESS";
export const EDIT_FINANCE_ERROR = "EDIT_FINANCE_ERROR";

export const CLEAR_FILTERS = "CLEAR_FILTERS";